/* PROBLEM 2 [ https://projecteuler.net/problem=2 ]
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will be
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * SOLUTION: Brute force summation
 * This solution tests all terms of the Fibonacci sequence less than a given
 * value to test for divisibility with the supplied arguments. Using a divisor
 * of 2 is sufficient to answer the above question.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
 
/* INCLUDES */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/* TYPE DEFINITIONS */
typedef long double   DATA;
#define DATA_FORMAT   "%.0Lf"
typedef unsigned long INDEX;
#define INDEX_FORMAT  "%lu"

/* OUTPUT STRINGS */
#define USAGE_STR   "usage: %s [max] [divisor(s)]\n"
#define ARGS_FAIL   "ERROR: %s only operates on positive integers!\n"
#define OPT_FAIL    "ERROR: Memory allocation failure during optimization!\n"

/* FUNCTION PROTOTYPES */
DATA   *optimize_divisors (DATA *set, INDEX *set_size);
INDEX  is_multiple        (DATA n, DATA *set, INDEX set_size);
DATA   brute_force_sum    (DATA *divisors, INDEX num_divisors, DATA max);

/* BEGIN PROGRAM * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* optimize_divisors(set, set_size)
 * Flags and removes any elements in the given set that are
 * divisible by some other element in the set, for eliminating
 * duplicated matches when using the fast summation formula.
 */
DATA *optimize_divisors (DATA *set, INDEX *set_size)
{
  /* Declarations and initializations */
  DATA *optimized_set;
  INDEX optimized_set_size, orig_set_size, i, j;
  optimized_set_size = *set_size; orig_set_size = *set_size;

  /* Pass through input set and flag divisible values */
  for (i = 0; i < orig_set_size; i++)
    for (j = 0; j < orig_set_size; j++)
    {
      if ((j == i) || set[j] == -1) continue;
      if ((fmod(set[i],set[j]) == 0) || set[i] < 1) 
        { set[i] = -1; optimized_set_size--; break; } 
    }

  /* Allocate new optimized set with null terminator */
  optimized_set = (DATA *)calloc(optimized_set_size+1,sizeof(DATA));
  if (!optimized_set) { printf(OPT_FAIL); return set; }

  /* Copy remaining values in old set to new set */
  j = 0; for (i = 0; i < orig_set_size; i++)
    if (set[i] > 0) { optimized_set[j] = set[i]; j++; }

  /* Print contents of optimized array */
  printf("Optimized search: {");
  for (i = 0; i < optimized_set_size; i++)
  { 
    printf("%.0Lf",optimized_set[i]);
    if (i != optimized_set_size - 1) printf(", ");
  } 
  printf("} (%lu byte",optimized_set_size*sizeof(DATA));
  if (optimized_set_size*sizeof(DATA) != 1) printf("s");
  printf(")\n");

  /* Clean up old set, adjust set size and return the new set */
  free(set); *set_size = optimized_set_size; return optimized_set;
}

/* is_multiple (n, set, set_size)
 * Determines if n is a multiple of any member of the given set.
 * Used in brute force fallback solution.
 */
INDEX is_multiple (DATA n, DATA *set, INDEX set_size)
{
  INDEX i; for (i = 0; i < set_size; i++)
    if (fmod(n,set[i]) == 0) return 1;
  return 0;
}

/* brute_force_sum(divisors,num_divisors,max)
 * Performs a brute force search of terms in the Fibonacci
 * Sequence divisible by the input set in the range 
 * 0 < n < max
 */
DATA brute_force_sum (DATA *divisors, INDEX num_divisors, DATA max)
{
 DATA n, sum, matches, prev, last_prev; 
 sum = 0; matches = 0; prev = 2; last_prev = 1;
 
 /* Check first two fibonacci terms against the divisors */
 if (is_multiple(last_prev,divisors,num_divisors)) { sum += last_prev; matches++; }
 if (is_multiple(prev,divisors,num_divisors)) { sum += prev; matches++; }
 
 /* Begin main loop */
 for (n = prev + last_prev; n <= max; n = prev + last_prev) 
 {
   if (is_multiple(n,divisors,num_divisors)) { sum += n; matches++; }
   last_prev = prev; prev = n;
 }
 
 /* Print match statistic and return */
 printf("Matches in range: " DATA_FORMAT "\n",matches);
 return sum;
}

/* MAIN FUNCTION
 * Takes in the maximum value as the first argument and arbitrary 
 * target divisors in subsequent arguments. Keeps track of and
 * prints sum of matching numbers when loop is completed.
 */
int main (int argc, char **argv)
{
  /* Variable declarations and setup */
  DATA max, sum, *divisors;
  INDEX i, num_divisors;

  /* Argument parsing */
  if (argc < 2) { printf(USAGE_STR,argv[0]); return 0; }
  max = floor(atof(argv[1]))-1;
  if (max < 1) { printf(ARGS_FAIL,argv[0]); return 0; }
  num_divisors = argc-2;
  divisors = (DATA *)calloc(num_divisors,sizeof(DATA));
  for (i = 0; i < num_divisors; i++) 
  { 
    divisors[i] = floor(atof(argv[i+2]));
    if (divisors[i] < 1) { printf(ARGS_FAIL,argv[0]); return 0; }
  }

  /* Print pre-run statistics */
  printf("Testing range:    0 < n < " DATA_FORMAT "\n",max+1);
  printf("Data size:        " INDEX_FORMAT " bits\n",(INDEX)sizeof(DATA)*8);

  /* Optimize divisor set */
  divisors = optimize_divisors(divisors,&num_divisors);

  /* Compute sum */
  sum = brute_force_sum(divisors,num_divisors,max);

  /* Result return and cleanup */ 
  printf("Sum of matches:   " DATA_FORMAT "\n",sum);
  free(divisors); return 0;
}
