# COMPILER CONFIGURATION // COMPILER CONFIGURATION // COMPILER CONFIGURATION #
CC         = c89
CC_VER     = HP C
CFLAGS     = 
OFLAGS     = +O3

#  COMPILER FLAGS  //  COMPILER FLAGS // COMPILER FLAGS  //  COMPILER FLAGS  #
CC_OUT     = -o
CC_DEFINE  = -D
CC_LIB     = -l
